### ISSUE TITLE
incorporate stylus as an override

### ISSUE THREAD

**Issue by roni-estein** [DevMarketer/DevMarketer#10]
Hi Alex, as a feature request, are you able to show how you might do your overrides in stylus, and still use laravel mix or webpack to merge them into a single css file? I've been running against this trying to  incorporate bulma with some of our existing libraries.

To clarify, since bulma is written in sass, and some other libraries stylus or less, pulling them all together into a vendor.css has been a real challenge. This is doable in gulp since it's simpler to chain method together and also to move things out of the public folder.

With laravel mix, or webpack if you operate on an output file, even if it's an intermediary staging file you are triggering a change. Which make it impossible to use something like npm run watch, since it re-triggers itself.

Thanks for the great tutorials.

**Comment by jacurtis** [comment]
I really haven't done much with stylus. But here is what I would suggest.

Try to compile your sass, then your stylus both into css files, and then combine them together as css files.

```javascript
mix.sass('resources/scss/bulma.scss', 'resources/css/bulma.css')
   .stylus('resources/stylus/custom.styl', 'resources/css/custom.css')
   .styles([
        'resources/css/bulma.css',
        'resources/css/custom.css'
    ], 'public/css/app.css');
````

This takes sass and converts it to css and puts it in your resources folder. Then it compiles your stylus into css and puts it in your resource folder, then it combines them together into one file and puts it into your public folder.

I haven't tested this, so I am not sure it would work. But this is where I would start.

**Comment by roni-estein** [comment]
Thanks, but the problem with mix is you can’t put things back in resources as an output. Or at least that was the case when I was playing with this one. I’ll try it again and let you know.

**Comment by jacurtis** [comment]
I will have to experiment with it then. I havent mixed preprocessors before to be honest. I always use SASS, so i have been lucky in that way.
