### ISSUE TITLE
Scripts in package.json need updating.

### ISSUE THREAD

**Issue by Taramouse** [DevMarketer/DevMarketer#13]
Running php `artisan run dev` still not working. Scripts need updating as mentioned in the video.

```
"scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
```

**Comment by jacurtis** [comment]
I am super confused how this didn't get committed to the repo. I thought i did it on the video, but I am looking now and it seems like it hasnt been done. I am going to accept the 7dad15d pull request and it should work then.

**Comment by jacurtis** [comment]
Ill have to move the episode 16 tag to this commit but otherwise this is done. Thanks to @Taramouse for doing that.

**Comment by Taramouse** [comment]
Happy to help, thank you.

**Comment by Taramouse** [comment]
I saw you do it in the video so was also confused when I realised t was the scripts were not working.

**Comment by ghost** [comment]
'cross-env' is not recognized as an internal or external command,
