### ISSUE TITLE
Unknown custom element: <b-checkbox-group>

### ISSUE THREAD

**Issue by tashi007** [DevMarketer/DevMarketer#22]
When I clone your repository, and when running the application, I see following errors under edit roles and edit users page

[Vue warn]: Unknown custom element: <b-checkbox-group> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <Root>)
 http://127.0.0.1:8000/js/app.js:19621

How do I resolve this. 
Thanks

**Comment by jacurtis** [comment]
Have you ran `npm install` yet and then compiled with `npm run dev`?

After that you also need to make sure that you have instantiated a Vue object on the page that you are trying to use the component in.

So at the bottom of the page you need to do something like:

```js
let app = new Vue({
    el: '#app',
    data: {}
});
```

In this example you need the component to be somewhere inside the `#app` div.

**Comment by hiimfish** [comment]
https://github.com/rafaelpimpa/buefy/releases/tag/v0.5.0

> Removed CheckboxGroup
> Removed RadioGroup

need update this
```
<div class="block">
        <b-radio v-model="permissionType" native-value="basic" name="permission_type">Basic Permission</b-radio>
        <b-radio v-model="permissionType" native-value="crud" name="permission_type">CRUD Permission</b-radio>
</div>
```

**Comment by jacurtis** [comment]
Good catch. We will need to go back and fix that. If you (or anyone) wants to submit a PR with the fixes than I will review and accept it. Otherwise I will get to it at some point.
I actually remember running into this problem on another project now, but it slipped by me on this project.

**Comment by memestrict** [comment]
for laravel 5.8 with follow up this guide

just replace it to

```
<b-radio v-model="permissionType" native-value="basic" name="permission_type">Basic</b-radio>
<b-radio v-model="permissionType" native-value="crud" name="permission_type">CRUD</b-radio>
```

1.remove the `**b-checkbox-group**`
2.apply` **v-model** to all **b-radio**`
3.try to fix the `**:value** , **custom-value**` or something...
if it give your error, just apply them at` **native-value**`

**Comment by josekay** [comment]
Thanks so much Alex. I think you should add a donate option so that we can contribute the little we can afford for all the hours you put in to make these awesome tutorials. I have indeed learnt alot

**Comment by josekay** [comment]
For the Auto-Generate Password, how do you know the password that was auto-generated?
