### ISSUE TITLE
Any Reason not to add composer lock?

### ISSUE THREAD

**Issue by shirshak55** [DevMarketer/DevMarketer#30]
I guess we should add composer file so that it will not create any problem between your version and our version due to dependency? I guess we can add it.

I think you probably don't added because this is in development and you may want to get latest version always. But it may work for you and not for us due to dependencies problem .

For other who don't understand lock files.
https://daylerees.com/the-composer-lock-file/

Thanks Alex will be following videos :)

**Comment by mario-fehr** [comment]
see here #24

**Comment by ghost** [comment]
This also bugs me, isn't it a universal fact that lockfiles keep your code stable?

**Comment by jacurtis** [comment]
What I'm going to do is commit the lock file myself but have the .gitignore file block them so that when people submit PRs I'm not always getting a different lock file.
So I'll recommit the lock file in a moment but I'll manually manage it instead of getting new ones with ever new Pull request.

**Comment by jacurtis** [comment]
Ok, composer.lock is back in the project. I was trying to avoid getting new .lock files from every new pull request. This should alleviate that problem while still providing a composer.lock for new clones and composer install commands that you run.

Normally, as a matter of practice when you are working as a team, it is recommended to commit the lock file, just FYI.
