### ISSUE TITLE
Style sheet for manage.scss

### ISSUE THREAD

**Issue by almurillo** [DevMarketer/DevMarketer#32]
once the app is on mobile the left menu hides however the managment-area does not take advantage of the new real state when the left menu is gone. I had added this code to the manage.scss file to take advantage of that.

`.management-area {
  top: 4rem;
  right: 0;

  @include desktop {
    position: absolute;
    left: 200px;
  }

}`

**Comment by mario-fehr** [comment]
I think it would be a good idea to open a PR for this.

**Comment by jacurtis** [comment]
Thanks for this. Indeed I forgot to add this during the video. Ill add some code to fix this in the upcoming video. Since I didnt have content in the frame to remind me, i forgot to get rid of the positioning on the left for the main content area.

**Comment by jacurtis** [comment]
This was resolved with #33 which has been merged into dev branch (and soon master).
