### ISSUE TITLE
[Task]: Login Page has Checkbox That Doesn't Render

### ISSUE THREAD

**Issue by jacurtis** [DevMarketer/DevMarketer#35]
On this page: http://devmarketer.dev/login the "Remember me" checkbox doesn't render. It's probably something minor with Vue.js not being initiated or something silly like that. Should be easy to fix.

**Comment by raniesantos** [comment]
I want to submit a PR to fix this but I don't know how to exclude my previous commit so only the changes from my latest commit is included.
The fix is simple, there's no vue instance on that page, just add:
```
@section('scripts')
  <script>
    var app = new Vue({
      el: '#app'
    });
  </script>
@endsection
```

**Comment by amc123-glitch** [comment]
Is there a certain version I should be using for this to work? I am currently using Laravel 5.6.* and "vue": "^2.5.16" and still the actual checkbox for the login, user password (in the create user section), or any other spot with checkboxes won't render the checkbox but renders the text inside of the checkbox. On top of that it is still not able to disable/enable inputs.

In addition, I get this error in the console on any blade page with vue on it:
> Uncaught ReferenceError: Vue is not defined
>     at login:83


Yet my app.js file looks exactly like yours with the window vue portion. This worked for a few seconds and then when I refreshed the browser  at one point all checkboxes stopped working
