### ISSUE TITLE
Observer not working

### ISSUE THREAD

**Issue by sinrise** [DevMarketer/DevMarketer#62]
As of Laravel 5.7, the UserObserver is not adding the API token when creating a new user and Laravel is throwing the 'no default value' error.

**Comment by memestrict** [comment]
ive got this issue too, any suggestion?
at **laravel 5.8**

solved guide
apply **nullable** to api_token migration
`$table->string('api_token', 60)->unique()->nullable();`

**Comment by arunmadathil** [comment]
unique()->nullable(); doesn't true for all database except mysql.

**Comment by memestrict** [comment]
> unique()->nullable(); doesn't true for all database except mysql.

oh, sorry, i dont have experience for other DB and just follow up this tutorial and try to fix errors.
