### ISSUE TITLE
Auto generate password refactoring suggestion (my first github issue  post!) 

### ISSUE THREAD

**Issue by valdsign** [DevMarketer/DevMarketer#7]
i have suggestion to refactoring auto generate password in UserController, i notice auto generated password codes is being called twice in UserController. 
so instead of doing this
```
if (!empty($request->password)) 
{ 

   $password = trim($request->password);

} else {

   $length = 10;
   $keyspace = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ';
   $str = '';
   $max = mb_strlen($keyspace, '8bit') - 1;
   
   for ($i = 0; $i < $length; ++$i) 
   {
       $str .= $keyspace[random_int(0, $max)];
   }   
   $password = $str;
}

```

how about creating small function like this one

```
private function generateAutoPassword()
    {

      #set manual password
      $length   = 10;
      $keyspace = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ';
      $str      = '';
      $max      = mb_strlen($keyspace, '8bit') - 1;
      for ($i=0; $i < $length; ++$i)
      {
        $str    .= $keyspace[random_int(0, $max)];
      }
      return $str;
    }
```

and then call them whatever function that need dem function like for example, when we need to check user creation process, if user provide costum password then store them in db or else run auto generate password function and then store them in db, like this one.
```
if ($request->has('password') && !empty($request->password))
 {
      $password = trim($request->password);
  }  else {
       $password = $this->generateAutoPassword();
  }
```
and then another check if password is provide or not, and then store them in db
```
if ($request->has('password') && !empty($request->password)) 
{
       $user->password = Hash::make($request->password);

} else {

        $user->password = Hash::make($password);

}
```
i hope this is make sense to you alex. if you find this suggestion is silly, please give me feed back & also forgive my broken english.

**Comment by valdsign** [comment]
i notice my silly mistakes, why would I make password checking twice, in the auto generate password section and storing data to $user-password section. this is embarrassing :expressionless:

**Comment by Ratko-Solaja** [comment]
Alex already mentioned that in the video. :) He wasn't planing on doing it at that moment, but he did say he will do it later.

What you can do is create an Helpers.php file in app/Http/ and then add it to the autoload section in composer.json

After that you need to dump autoload and everything should work as expected.

**Comment by valdsign** [comment]
@Ratko-Solaja yes, i wasn't watch the video until the end, as soon as i notice the repetition i post above suggestion. 

i'm new to laravel so the only thing that i know that i can do is creating simple function or method inside another class & call them inside UserController. anyway I hope alex do show us how to create helper in another video.

**Comment by Ratko-Solaja** [comment]
I'm not an expert in Laravel myself, that's why I'm watching the videos. :)

**Comment by jacurtis** [comment]
Thanks for pointing this out. The repetition was actually intentional because in a few videos I was going to teach how to make helper functions and then extract this to a helper function to remove the repetition.

The code looks good though, thanks for noticing that and pointing it out here.
