### ISSUE TITLE
Vue not working in auto generate password

### ISSUE THREAD

**Issue by nikhildhakal** [DevMarketer/DevMarketer#9]
Many have commented on the youtube comments of Vue not working. Similar problem exists in my code.
Even after adding
var app = new Vue({
  el: '#app',
  data: {}
}); to app.js, vue isnt completely working. 
Doing :disabled="auto_password" seem to work as it doesn't display the password input. But when I click checkbox, the input element is not hiding or showing. Same result for v-if="auto_password".

**Comment by caleboki** [comment]
Has anyone been able to solve this issue?

**Comment by mjcarter95** [comment]
Caleboki - I'm not sure why you're experiencing this issue, I followed the tutorials & I don't have the issue that is described here. I uploaded my code to jsfiddle, you can access it at the following URL https://jsfiddle.net/myrcgeh4/ 

Hope this helps!

**Comment by caleboki** [comment]
@mjcarter92 I just fixed it a few minutes ago. I somehow had two Vue instances running that was why it wasn't working. Thanks anyway
